### ISSUE TITLE
Add CI to the project

### ISSUE THREAD

**Issue by jbw** [ocharles/dhall.js#2]
We should integrate something like CircleCi to automate the building a running of tests.

**Comment by ocharles** [comment]
Sounds good to me. Got any preference?

**Comment by jbw** [comment]
I like CircleCI but either that or Travis are well supported.

**Comment by ocharles** [comment]
Cool, do I need to do anything to add it to CircleCI? Is it the same as needing a `.travis.yml`?

**Comment by jbw** [comment]
Yeah. CircleCi has some steps you need to follow (copy a config it generates) when your sign up and add your github project. You can look at https://github.com/jbw/hypertonic/tree/master/.circleci for what it will eventually look like. CircleCi should provide the config with the correct values though.

**Comment by ocharles** [comment]
I get this - https://circleci.com/gh/ocharles/dhall.js/2

I need to generate the parser, but not sure what to do about npx missing.

**Comment by jbw** [comment]
@ocharles  also update the package.json to not use npx and just run pegjs. Isn't a needed dependency i think.

**Comment by jbw** [comment]
Normally you would add npx as a dev dependency so when CircleCi run the install script it gets added but i don't think it actually needs npx to run pegjs.

**Comment by ocharles** [comment]
Sorted, thanks!
